questa: clean
	qverilog -f flist
clean:
	\rm -fr work* qver* *.wlf

rvra: clean
	vsim -c -do rvra_run.do
rvra1:clean
	vsim -c -do rvra1_run.do
rvra2:clean
	vsim -c -do rvra2_run.do
rvra1_b:clean
	vsim -c -do rvra_run_b.do
rvra1_b1:clean
	vsim -c -do rvra_run_b1.do
rvra1_b2:clean
	vsim -c -do rvra_run_b2.do
