/********************************************
* VerifWorks Go2UVM App: VW_DVC_Go2UVM
* Automatically generated by VerifWorks's DVC_Go2UVM Riviera Apps 
* Thanks for using VerifWorks products
* Visit http://www.verifworks.com for more 
* Generated on   : 2016-05-28 14:19:14
********************************************/ 



// Generating SystemVerilog interface for module: simple
// ---------------------------------------------------------
interface simple_if (input logic clk);
  logic  [0:0] a;
  logic  [0:0] a0;
  logic  [0:0] a1;
  logic  [0:0] a2;
  logic  [0:0] a4;
  logic  [0:0] a5;
  logic  [0:0] ack;
  logic  [0:0] b;
  logic  [0:0] b0;
  logic  [0:0] busy;
  logic  [0:0] c;
  logic  [0:0] crc_err;
  logic  [0:0] crc_pass;
  logic  [0:0] d;
  logic  [0:0] done;
  logic  [31:0] i;
  logic  [31:0] j;
  logic  [0:0] ready;
  logic  [0:0] req;
  logic  [0:0] reset;
  logic  [0:0] reset_n;
  logic  [0:0] x;
  logic  [0:0] x0;
  logic  [0:0] x1;
  // End of interface signals 


  // Start of clocking block definition 
  clocking cb @(posedge clk);
    output a;
    output a0;
    output a1;
    output a2;
    output a4;
    output a5;
    output b;
    output b0;
    output busy;
    output c;
    output crc_err;
    output crc_pass;
    output d;
    output done;
    output i;
    output j;
    output ready;
    output req;
    output reset;
    output reset_n;
    output x;
    output x0;
    output x1;
  endclocking : cb
  // End of clocking block definition 

endinterface : simple_if
// Automatically generated from VerifWorks's DVCreate-Go2UVM product
// Thanks for using VerifWorks products, see http://www.verifworks.com for more

import uvm_pkg::*;
`include "uvm_macros.svh"
// Import Go2UVM Package
import vw_go2uvm_pkg::*;
// Use the base class provided by the vw_go2uvm_pkg
class simple_test extends go2uvm_base_test;
  // Create a handle to the actual interface
  virtual simple_if vif;
  task reset;
    `uvm_info (log_id, "Start of reset", UVM_MEDIUM)
   // `uvm_info (log_id, "Fill in your reset logic here ", UVM_MEDIUM)
     this.vif.cb.reset <= 1'b0;
     repeat (5) @ (this.vif.cb);
     this.vif.cb.reset <= 1'b1;
     repeat (1) @ (this.vif.cb);
    `uvm_info (log_id, "End of reset", UVM_MEDIUM)
  endtask : reset
  task main ();
    `uvm_info (log_id, "Start of main", UVM_MEDIUM)
   // `uvm_info (log_id, "Fill in your main logic here ", UVM_MEDIUM)
    
	@(vif.cb);
		begin
		  @(vif.cb);
			vif.cb.a <= 1'b1;
			vif.cb.a1 <= 1'b1;
			vif.cb.a2 <= 1'b0;
		  @(vif.cb);
		  @(vif.cb);
			vif.cb.a1 <= 1'b1;
			vif.cb.a2 <= 1'b0;
		  @(vif.cb);
			vif.cb.a1 <= 1'b1;
			vif.cb.a2 <= 1'b1;
		  @(vif.cb);
		  @(vif.cb);
			vif.cb.a1 <= 1'b0;
		end

   #300 $finish;
  `uvm_info (log_id, "End of main", UVM_MEDIUM)
  endtask : main
endclass : simple_test

module simple_go2uvm;
  timeunit 1ns;
  timeprecision 1ns;
  parameter VW_CLK_PERIOD = 10;

  // Simple clock generator
  bit clk ;
  always # (VW_CLK_PERIOD/2) clk <= ~clk;

  // Interface instance
  simple_if simple_if_0 (.*);

  // Connect TB clk to Interface instance clk

  // DUT instance
  simple simple_0 (.clk(clk),
                    .req(simple_if_0.req),
                    .ack(simple_if_0.ack),
                    .crc_pass(simple_if_0.crc_pass),
                    .crc_err(simple_if_0.crc_err),
                    .busy(simple_if_0.busy),
                    .reset(simple_if_0.reset),
                    .ready(simple_if_0.ready),
                    .x(simple_if_0.x),
                    .a(simple_if_0.a),
                    .b0(simple_if_0.b0),
                    .c(simple_if_0.c),
                    .b(simple_if_0.b),
                    .d(simple_if_0.d),
                    .x0(simple_if_0.x0),
                    .x1(simple_if_0.x1),
                    .a1(simple_if_0.a1),
                    .a2(simple_if_0.a2),
                    .a0(simple_if_0.a0),
                    .a5(simple_if_0.a5),
                    .a4(simple_if_0.a4),
                    .reset_n(simple_if_0.reset_n),
                    .i(simple_if_0.i),
                    .j(simple_if_0.j));


  // Using VW_Go2UVM
  simple_test simple_test_0;
  initial begin : go2uvm_test
    simple_test_0 = new ();
    // Connect virtual interface to physical interface
    simple_test_0.vif = simple_if_0;
    // Kick start standard UVM phasing
    run_test ();
  end : go2uvm_test
endmodule : simple_go2uvm

