/********************************************
* VerifWorks Go2UVM App: VW_DVC_Go2UVM
* Automatically generated by VerifWorks's DVC_Go2UVM Riviera Apps 
* Thanks for using VerifWorks products
* Visit http://www.verifworks.com for more 
* Generated on   : 2016-05-27 13:38:43
********************************************/ 



// Generating SystemVerilog interface for module: always_prop
// ---------------------------------------------------------
